---
title: "index_recovery"
author: "Marina"
date: '2022-12-18'
output: html_document
---

##### load packages and data
{code not included}
```{r packages and data, message=FALSE, include=FALSE}
library(tidyverse)
library(mgcv)
library(sf)
#library(lwgeom)
library(lme4)
library(ggsci)
#library(ggrepel)
library(stats)
#library(broom)
#library(gghighlight)
library(gamm4)
#library(MuMIn)
library(cowplot)
library(MASS) #for glm.nb
library(pscl) #for zero-inflated glm
library(lmtest) #for lrtest: likelihood test of nested models
library(VGAM) #for zero-truncated models
library(countreg) #for zero-truncated models
library(glmmTMB) #glmm with zero-truncated nb
library(DHARMa) #diagnostic for mixed regression models
library(emmeans)

setwd("~/GitHub/desert-fires-impact-biodiversity")

sm_mam <- c("Ammospermophilus", "Xerospermophilus", "Dipodomys", "Vulpes")
raptors  <- c("Accipitriformes", 'Pelecaniformes', "Strigiformes", "Falconiformes")

animals <- st_read("shapefiles/animals/animals_51022.shp") %>% 
  st_drop_geometry() %>% 
  rename(obsID = TARGET_FID, order = order_, 
         individualCount = individual, obsDay = day, 
         obsMonth = month, obsYear = year, 
         institutionalCode = institutio, 
         treatmentGroup = treatmentG, fireName = INCIDENT, 
         fireYear = FIRE_YEARn, fireSize = GISAcres) %>% 
  dplyr::select(-c("verbatimSc", "issue", "coordinate", 'nearRd_FID', "nearUA_FID", 
            'basisOfRec', 'institutionalCode', 'collection', 'recordedBy', 'nearRdDist', 'nearUADist')) %>% 
  filter(obsYear > 1994, obsYear < 2021, species != "Canis lupus", species != "Balaenoptera musculus", 
         species != "Grus canadensis", treatmentGroup != "burned prior 2000") %>%  
  mutate(simplified_taxa =
                     ifelse(genus == "Puma" | genus == "Ovis", "Large Mammals",
                            ifelse(genus == "Branchinecta" | genus == "Cyprinodon", "Aquatic",
                            ifelse(genus == "Dinacoma", "Beetles",
                            ifelse(genus == "Bombus", "Bees",
                            ifelse(genus == "Gopherus", "Tortoises",
                            ifelse(genus == "Danaus" | genus == "Euproserpinus", "Butterflies & Moths",
                            ifelse(genus == "Rana" | genus == "Anaxyrus","Frogs and Toads",
                            ifelse(genus == "Ambystoma" | genus == "Batrachoseps", "Salamanders",
                            ifelse(genus == "Coleonyx" | genus == "Gambelia" | genus == "Uma", "Lizards and Geckos",
                            ifelse(genus %in% sm_mam, "Small Mammals",
                            ifelse(order %in% raptors, "Birds:Raptors",
                            ifelse(order == "Passeriformes", "Birds:Passerines",
                            ifelse(order == "Piciformes", "Birds:Woodpeckers",
                            ifelse(order == "Gruiformes" | order == "Anseriformes", "Birds:Rails and Geese", "ERROR"
                                   )))))))))))))),
         ez_taxa = ifelse(class=='Aves', 'Aves', 'Other'),
         individualCount = ifelse(individualCount == 0, 1, individualCount))


ndvi <- read_csv("data/ndvi.csv")
areas <- read.csv('data/areas.csv')
sites <- read_csv("data/sites.csv")


data2a <- animals %>%
  group_by(obsYear, simplified_taxa, ez_taxa, treatmentGroup, desert) %>% 
  summarize(totalObs = sum(individualCount))

data <- data.frame(obsYear = rep(1995:2020, each = 84),
                    desert = rep(rep(c("Mojave", "San Joaquin", "Sonoran"), each = 2), times = 364),
                    treatmentGroup = rep(rep(c("burned", "never burned"), times = 42), times = 26),
                    simplified_taxa = rep(rep(c("Large Mammals", "Aquatic","Beetles", "Bees", "Tortoises",
                                                "Butterflies & Moths", "Frogs and Toads", "Salamanders",
                                                "Lizards and Geckos", "Small Mammals", "Birds:Raptors",
                                                "Birds:Passerines", "Birds:Woodpeckers", 
                                                "Birds:Rails and Geese"), each = 6), times = 26))%>% 
  left_join(., ndvi, by = c("desert", "obsYear", "treatmentGroup")) %>% #add ndvi
  left_join(., areas, by = c("desert", "treatmentGroup")) %>% #add area
  left_join(., data2a, by = c("desert", "obsYear", "treatmentGroup", "simplified_taxa")) %>% #add data 
  mutate(ez_taxa = ifelse(startsWith(simplified_taxa, "Birds"), "Aves", "Other")) %>% #category Aves and Other
  mutate(totalObs = ifelse(is.na(totalObs), 0, totalObs)) %>%  # Total Obs NA -> 0 
  mutate(stzd_totalObs = (totalObs * 1000)/area_km2, #standardize observations
         desert = as.factor(desert),
         treatmentGroup = factor(ifelse(startsWith(treatmentGroup, "never"), "Control", "Burned"), 
                                 levels = c( "Control", "Burned")),
         simplified_taxa = as.factor(simplified_taxa),
         ez_taxa = as.factor(ez_taxa),
         stzdTotalObs_rounded = ceiling(stzd_totalObs))

data_2000 <- filter(data, obsYear > 1999) # filter out anything before 2000 since no NDVI info

```
```{r prepare recovery data, include = FALSE}
data_r <- animals %>% 
  filter(treatmentGroup == "burned") %>% 
  merge(.,sites[,c("fireID", "fireMonth")], by = "fireID") %>% #NEED to add fire months
  mutate(yearsSinceFire = obsYear - fireYear, 
         pre_or_post = case_when(yearsSinceFire > 0 ~ "post",
                                 yearsSinceFire < 0 ~ "pre",
                                 yearsSinceFire == 0 ~ "SY"),
         n_years = abs(yearsSinceFire))

#find pre- post- for observations in the same year and replace SY in datafire with pre or post
SY <- filter(data_r, yearsSinceFire == 0) %>% 
  mutate(postingmonth = obsMonth - fireMonth,
    pre_or_post = case_when(postingmonth >0 ~ "post",
                            postingmonth < 0 ~ "pre",
                            yearsSinceFire == 0 ~ "SM"))
data_r$pre_or_post <- ifelse(data_r$pre_or_post == "SY", SY$pre_or_post, data_r$pre_or_post)
unique(data_r$pre_or_post) #check if any SM (same month); would need to further categorize

data_r <- left_join(data_r, ndvi, by = c("desert", "obsYear", "treatmentGroup"))

###data for pre-/post- burned sites
data_pp_b1 <-  data_r %>% 
  filter(n_years <=5, 
         simplified_taxa == 'Birds:Raptors' | simplified_taxa == 'Birds:Passerines') %>% 
  dplyr::select(c("ez_taxa", "simplified_taxa", "individualCount", 
                  "obsYear", "desert", "fireID", 
                  "fireName", "fireYear", "fireMonth", 
                  "yearsSinceFire", "pre_or_post", "n_years", "ndvi")) %>% 
  group_by(desert, obsYear, fireID, 
           fireYear, yearsSinceFire, 
           ez_taxa, simplified_taxa, 
           pre_or_post, n_years, ndvi) %>% 
  summarize(totalObs = n()) %>% 
  left_join(., filter(areas, treatmentGroup == "burned"), by = "desert") %>% #add area
  mutate(stzdObs = ceiling((totalObs/area_km2)*10000)) %>% 
  ungroup() %>% group_by(desert)

### add zeros for years with no occurrences reported
fireYear <- data_pp_b1 %>% filter(n_years <=5) %>% group_by(fireYear, desert, fireID) %>% summarize(total = n()) %>% dplyr::select(-total) %>% filter(fireYear <= 2015)

data_pp_b2 <- data.frame(rep(fireYear$fireYear, each = 22), rep(fireYear$desert, each = 22), rep(fireYear$fireID, each = 22), rep (c('Birds:Raptors','Birds:Passerines'), each = 11, times = nrow(fireYear)))

names(data_pp_b2)[1] <- "fireYear"
names(data_pp_b2)[2] <- "desert"
names(data_pp_b2)[3] <- "fireID"
names(data_pp_b2)[4] <- "simplified_taxa"

#second column = list of +/- since fire / from -5 to +5
data_pp_b2$yearsSinceFire<- rep(-5:5, nrow(fireYear))

#make a column with obsYear
data_pp_b2 <- data_pp_b2 %>% mutate(obsYear = fireYear + yearsSinceFire)

#merge the occurrences for burn sites with the data frame created and replace with zeros when no occurrences were reported

data_pp_b2<- left_join(data_pp_b2, data_pp_b1, by = c("desert", "obsYear", "fireYear", "fireID", "yearsSinceFire", "simplified_taxa")) %>% 
  filter(yearsSinceFire != 0 | yearsSinceFire == 0 & !is.na(pre_or_post)) %>% 
  mutate(treatmentGroup = ifelse(is.na(treatmentGroup), "burned", treatmentGroup),
         pre_or_post = ifelse(is.na(pre_or_post), case_when(yearsSinceFire > 0 ~ "post",
                                 yearsSinceFire < 0 ~ "pre",
                                 yearsSinceFire == 0 ~ "same year"), pre_or_post))

###data for pre-/post- control sites###

#first column = list of fireYear
###old code
# fireYear <- data_pp_b %>% filter(n_years <=5) %>% {unique(.$fireYear)} %>% sort() %>% rep(.,each=11)


data_c <- data.frame(rep(fireYear$fireYear, each = 22), 
                     rep(fireYear$desert, each = 22), 
                     rep(c('Birds:Raptors','Birds:Passerines'), each = 11, times = nrow(fireYear)))

names(data_c)[1] <- "fireYear"
names(data_c)[2] <- "desert"
names(data_c)[3] <- "simplified_taxa"

#second column = list of +/- since fire / from -5 to +5
data_c$yearsSinceFire<- rep(-5:5, nrow(fireYear))

#make a column with obsYear
data_c <- data_c %>% mutate(obsYear = fireYear + yearsSinceFire)


totalObs <- animals %>% 
  filter(treatmentGroup == "never burned") %>% 
  group_by(obsYear, desert, ez_taxa, simplified_taxa) %>% 
  summarize(totalObs = n())

data_c <- merge(data_c, totalObs) %>% mutate(pre_or_post = case_when(yearsSinceFire > 0 ~ "post",
                                 yearsSinceFire < 0 ~ "pre",
                                 yearsSinceFire == 0 ~ "same year")) %>% 
  left_join(., filter(ndvi, treatmentGroup == "never burned"), by = c("desert", "obsYear")) %>%#add ndvi
  dplyr::select(-treatmentGroup) %>% 
  left_join(., filter(areas, treatmentGroup == "never burned"), by = "desert") %>% #add area
  mutate(stzdObs = ceiling((totalObs/area_km2)*10000), treatmentGroup = "control",
         n_years = abs(yearsSinceFire),
         fireID = NA) %>% 
  filter(yearsSinceFire != 0)

data_pp <- rbind(data_pp_b2, data_c) %>% 
  mutate(pre_or_post = factor(pre_or_post, levels = c( "pre", "post")), 
         treatmentGroup = factor(treatmentGroup, levels = c("control", "burned")),
         desert = as.factor(desert),
         totalObs = ifelse(is.na(totalObs), 0, totalObs),
         stzdObs = ifelse(is.na(stzdObs), 0, stzdObs)) %>%  # Total Obs NA -> 0 )
  rename(funcGroup = simplified_taxa)
  

###data for over-time for burned sites

data_ot_b <- data_r %>% filter(yearsSinceFire >0) %>% 
  dplyr::select(c("ez_taxa", "simplified_taxa", "individualCount", "obsYear", "desert", "fireID", "fireName", "fireYear", "fireMonth", "yearsSinceFire", "pre_or_post", "n_years", "ndvi")) %>% 
  group_by(desert, obsYear, fireID, fireYear, yearsSinceFire, ez_taxa, simplified_taxa, pre_or_post, n_years, ndvi) %>% 
  summarize(totalObs = n()) %>% 
  left_join(., filter(areas, treatmentGroup == "burned"), by = "desert") %>% #add area
  mutate(stzdObs = ceiling((totalObs/area_km2)*10000)) %>% 
  ungroup() %>% group_by(desert)


###data for over time for control

test2 <- data_ot_b %>% group_by(desert, fireYear) %>% 
  summarize(maxTime = max(yearsSinceFire))


yearsSinceFire <- c()
desert <- c()
fireYear <- c()

for (i in 1:nrow(test2)) {
   yearsSinceFire <-  c(yearsSinceFire, rep(1:test2$maxTime[i], 1))
  }

for (i in 1:nrow(test2)) {
   desert <-  c(desert, rep(test2$desert[i], each = test2$maxTime[i]))
  }

for (i in 1:nrow(test2)) {
   fireYear <-  c(fireYear, rep(test2$fireYear[i], each = test2$maxTime[i]))
  }


data_ot_c <- data.frame(desert, fireYear, yearsSinceFire) %>% 
  mutate(obsYear = fireYear + yearsSinceFire) %>% 
  filter(obsYear < 2021) %>% 
  left_join(., totalObs, by = c("obsYear", "desert")) %>% 
  left_join(., filter(ndvi, treatmentGroup == "never burned"), by = c("desert", "obsYear")) %>%#add ndvi
  dplyr::select(-treatmentGroup) %>% 
  left_join(., filter(areas, treatmentGroup == "never burned"), by = "desert") %>% #add area
  mutate(stzdObs = ceiling((totalObs/area_km2)*10000), treatmentGroup = "control")

data_ot <- rbind(data_ot_b, data_ot_c) %>% 
  dplyr::select(-c(pre_or_post, n_years))
```
## Occurrences before and after fire

First graph below shows the overall occurrences of raptors and passerines between 1995-2020
Second graph shows the average number of occurrences reported 5 years before fire and 5 years after fire. Zeros were add to years when no occurrences were reported.

```{r prepost birds only data prep}



ggplot(data_pp, aes(x = treatmentGroup, y =  stzdObs, fill = factor(pre_or_post, levels = c("pre", "post")))) +
  geom_boxplot()+
  scale_fill_aaas(labels = c("Before fire", "After fire")) +
  #scale_x_discrete(labels = c("Burned", "Control")) +
  theme(legend.title = element_blank()) +
  xlab("Treatment Group") +
  ylab(bquote("Bird occurrences reported per 10,000 km"^2)) +
  facet_grid(vars(funcGroup),vars(desert))

#mean occurrences 5yrs before and after fire

data_pp_5yr <- data_pp %>% group_by(desert, fireYear, pre_or_post, funcGroup, treatmentGroup, fireID) %>% 
  summarize(mean_occurrence = ceiling(mean(stzdObs)))

ggplot(data_pp_5yr, aes(x = treatmentGroup, y =  mean_occurrence, fill = factor(pre_or_post, levels = c("pre", "post")))) +
  geom_boxplot()+
  scale_fill_aaas(labels = c("Before fire", "After fire")) +
  #scale_x_discrete(labels = c("Burned", "Control")) +
  theme(legend.title = element_blank()) +
  xlab("Treatment Group") +
  ylab(bquote("5-yr average of bird occurrences reported per 10,000 km"^2)) +
  facet_grid(vars(funcGroup),vars(desert))


```


##GLMM model

```{r stats on just birds recovery}

pp_nb1 <- glmmTMB(mean_occurrence ~ pre_or_post + treatmentGroup + funcGroup + (1|desert), family = nbinom1, data = data_pp_5yr)

#validate model using simulated residuals 
simulationOutput <- simulateResiduals(fittedModel = pp_nb1, plot = F)
plot(simulationOutput)

summary(pp_nb1)

#stepwise regression to select best predictors; both summary above and stepAIC show that funcGroup not significant
null <- glmmTMB(mean_occurrence ~ 1, family = nbinom1, data = data_pp_5yr)
stepAIC(pp_nb1, scope=list(lower=null, upper=pp_nb1), data=data_pp_5yr, direction='backward')



emm_pp <- emmeans(pp_nb1, ~ pre_or_post + treatmentGroup)
pp_tukey <- contrast(emm_pp, method ='pairwise')

summary(pp_tukey)

# tukey test of emmeans shows that: 
#   post-control is higher than pre-control with p-value 0.0021;
#   pre-burned is lower than pre-control with p-value <0.0001;
#   post-burnd is higher than pre-burned with p-value <0.0001

confint(pp_tukey)

plot(pp_tukey, xlab = "Difference in log(average occurrences in 5-yr period)")

```

