---
title: "Exploring effects of fire on endangered animals"
author: "Marina Goldgisser"
date: "8/23/2021"
output: html_document
---

Fire data polygons (or any spatial assets) spatially joined to biodiversity data from [GBIF](https://www.gbif.org) (or any similarly geocoded diversity data).

### Data  
First crack - birds.

```{r}
#libraries
library(tidyverse)
library(skimr)
library(lubridate)

#count data
sites <- read_csv("bronze.csv") 
firemonth <- sites %>% select(c("fireID", "fire_month")) #this creates a dataframe with fireID and firemonth
data <- read_csv("goldcounts.csv") %>%  
  left_join(., firemonth, by = "fireID") #joins the fire_month to the count data

#if need to convert NA to 1 for individual counts
#data$indvdlC[is.na(data$indvdlC)] = 1

#skim for QA/AC
skim(data)
#tidy  


tidy <- data %>% 
  select(c("fireID", "fireyear", "fire_month", "year", "month", "firesize", "n_observations")) %>% 
  rename(obsYear = "year", obsMonth = "month")

#specific to fire data now, calculate pre-post and absolute value of years 
tidy <- tidy %>% 
   mutate(offset = obsYear - fireyear, posting = case_when(offset > 0 ~ "post", offset < 0 ~ "pre", offset == 0 ~ "same year"), n_years = abs(offset)) %>% 
  na.exclude() %>% 
  distinct(fireyear, .keep_all= TRUE)
  
```

### Data viz  
EDA only for now.

```{r}
ggplot(tidy, aes(reorder(posting, n_observations), n_observations)) +
  geom_boxplot() + 
  stat_summary(fun.y=mean, geom="point", shape=18, size=5, color="red", fill="red") +
  labs(x = "posting", y = "n_observations")
ggplot(tidy, aes(n_years, n_observations, color = posting)) +
  geom_point() +
  geom_smooth(method = lm) +
  scale_color_brewer(palette = "Set1") +
  labs(x = "years before or after fire", y = "total count", color = "none")
tidy %>% 
  filter(posting == "post") %>% 
  ggplot(., aes(n_years, n_observations, color = posting)) +
  geom_point() +
  geom_smooth(method = lm) +
  scale_color_brewer(palette = "Set1") +
  labs(x = "years post fire", color = "", y = "n_observations") +
  theme(legend.position = "none")
```