---
title: "Control-Impact Spatial Point Pattern"
author: "Marina"
date: "4/20/2022"
output: html_document
---
```{r setup, include= FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)

```

```{r, load libraries and data}

library(tidyverse)
library(mgcv)
library(spatstat)
library(sf)
library(sp)
library(rgdal)
library(maptools)

setwd("~/GitHub/desert-fires-impact-biodiversity")

data_csv <- read_csv("data/animals_2022_v4.csv") %>% 
  select(-c(basisOfRecord, institutionCode, geometry, collection, recordedBy, issue)) %>% 
  filter(obsYear > 1994, obsYear < 2021)

data <- as.ppp(readShapeSpatial("shapefiles/animals_v4/animals_v4.shp"))
data_sj <- subset(data, desert == "San Joaquin")
data_moj <- subset(data, desert == "Mojave")
data_son <- subset(data, desert == "Sonoran")

data <- solist(data_sj, data_moj, data_son)

names(data) <- c("San Joaquin", "Mojave", "Sonoran")

deserts_sf <- readShapeSpatial("shapefiles/deserts/deserts_tf.shp")

deserts <- slot(readShapeSpatial("shapefiles/deserts/deserts_tf.shp"), "polygons") %>% 
  lapply(.,function(x) {SpatialPolygons(list(x)) } ) %>% 
  solapply(., as.owin)

#reorder deserts in list to match point pattern
sj <- deserts[[3]]
moj <- deserts[[2]]
son <- deserts[[1]]

deserts[[1]] <- sj
deserts[[2]] <- moj
deserts[[3]] <- son

fires <- slot(readShapeSpatial("shapefiles/fireshapefile/fires2000.shp"), "polygons") %>% 
  lapply(.,function(x) {SpatialPolygons(list(x)) } ) %>% 
  solapply(., as.owin)


```

##Pre-standardize variables observer bias and add post-fire value

```{r}
mon <- read.csv("data/site_months.csv")
names(mon)[1] <- "fireID" 
mon[1] <- as.factor(mon$fireID)

test <- list()

for (i in 1:3) {
  m <- marks(data[[i]]) %>% 
  #rename fields
  rename(obsYear = year, fireYear = FIRE_YEARn, 
         fireSize = GISAcres, fireName = INCIDENT, 
         obsDay = day, obsMonth = month, 
         order = order_, treatmentGroup = treatmentG) 
  #add fire month
  m <- left_join(m, mon, by = c("fireID", "fireName", "fireYear"))  

  
  #add column for years since fire and whether observation was pre- or post- fire
  for (r in 1:nrow(m)) {
    if (m$treatmentGroup[r] == 'burned') {
      m$yearsSinceFire[r] = m$obsYear[r] - m$fireYear[r]
      m$pre_or_post_fire[r] = case_when(m$yearsSinceFire[r] > 0 ~ "post-fire",
                                   m$yearsSinceFire[r] < 0 ~ "pre-fire",
                                   m$yearsSinceFire[r] == 0 ~ "SY")
      m$yearsSFAbs[r] = abs(m$yearsSinceFire[r])
    
      #create pre- and post- for observations that occurred in the same year
      SY <- filter(m, yearsSinceFire == 0) 
      if (length(SY) > 0) {
      SY <- SY %>% 
        mutate(yearsSinceFire = obsMonth - fireMonth,
             pre_or_post_fire = case_when(yearsSinceFire >0 ~ "post-fire",      
                                     yearsSinceFire < 0 ~ "pre-fire",
                                     yearsSinceFire == 0 ~ "SM"))
      m$pre_or_post_fire <- ifelse(m$pre_or_post_fire == "SY", SY$pre_or_post_fire, m$pre_or_post_fire)
      }
    } else {
      m$yearsSinceFire[r] = NA
      m$pre_or_post_fire[r] = NA
      m$yearsSFAbs[r] = NA
      }
  }
  marks(data[[i]]) <- m
}

#standardize nearest distance

for (i in length(data)) {
  m <- marks(data[[i]]) %>% 
     rename(nearestRdDist_m = nearRdDist, nearestUADist_m = nearUADist)
  
  m$stand.NEASREST_RD <- scale(m$nearestRdDist_m, center = TRUE, scale = TRUE)
  m$stand.NEAREST_URBAN <- scale(m$nearestUADist_m, center = TRUE, scale = TRUE)
  
  marks(data[[i]]) <- m
  
}




```


##Inspecting and exploring data

```{r}
# plot data
SON <- plot.ppp(data[[3]], main = "Occurrences reported 1995 - 2020;Sonoran Desert", clipwin = deserts[[3]], use.marks = FALSE, axes = TRUE, ann = TRUE, xlab = "latitude", ylab = "longitude")

MOJ <- plot.ppp(data[[2]], main = "Occurrences reported 1995 - 2020; Mojave Desert", clipwin = deserts[[2]], use.marks = FALSE, axes = TRUE, ann = TRUE, xlab = "latitude", ylab = "longitude")

SJ <- plot.ppp(data[[1]], main = "Occurrences reported 1995 - 2020; San Joaquin Desert", clipwin = deserts[[1]], use.marks = FALSE, axes = TRUE, ann = TRUE, xlab = "latitude", ylab = "longitude")

#all together
plot(data, main = "Occurrences reported 1995 - 2020", use.marks = FALSE)

#change window for point pattern
Window(data[[1]]) <- deserts[[1]]
Window(data[[2]]) <- deserts[[2]]
Window(data[[3]]) <- deserts[[3]]

#quadrat count and density intensity
QCDI_SJ <- solist(data[[1]], as.im(data[[1]], dimyx = 25), density(data[[1]]))
QCDI_MOJ <- solist(data[[2]],as.im(data[[2]], dimyx = 25),density(data[[2]]))
QCDI_SON <- solist(data[[3]], as.im(data[[3]], dimyx = 25), density(data[[3]]))

names(QCDI_SJ) <- c("Occurrences 1995-2020", "Quadrat Count", "Intensity")
names(QCDI_MOJ) <- c("Occurrences 1995-2020", "Quadrat Count", "Intensity")
names(QCDI_SON) <- c("Occurrences 1995-2020", "Quadrat Count", "Intensity")

plot(QCDI_SJ, axes=TRUE, clipwin = deserts[[1]], use.marks = FALSE)
plot(QCDI_MOJ, axes=TRUE, clipwin = deserts[[2]], use.marks = FALSE)
plot(QCDI_SON, axes=TRUE, clipwin = deserts[[3]], use.marks = FALSE)

plot(split(data[[1]], "class"), use.marks = FALSE)
plot(split(data[[1]], "treatmentGroup"), use.marks = FALSE)
plot(split(data[[2]], "treatmentGroup"), use.marks = FALSE)
plot(split(data[[3]], "treatmentGroup"), use.marks = FALSE)
plot(split(data[[1]], "pre_or_post_fire"), use.marks = FALSE)
plot(split(data[[2]], "pre_or_post_fire"), use.marks = FALSE)
plot(split(data[[3]], "pre_or_post_fire"), use.marks = FALSE)
```
Basic Summaries of point pattern
```{r}
plot(density(data[[1]]))

```


