---
title: "plants-at-fire-sites"
author: "Marina"
date: "12/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```

```{r, load libraries and data}
library(tidyverse)
library(vegan)

setwd("~/GitHub/desert-fires-impact-biodiversity")

sites <- read_csv("data/sites.csv")  %>%
  select(c(fireID, fireMonth, desert))
plants <- read_csv("data/plants-at-fire-sites.csv") %>% 
  left_join(sites, by = "fireID")

species <- plants %>% select(c(genus, species)) %>% 
  unique()

#filter plants for key native genus and key invasive species
native_genus <- c("Ephedra", "Yucca", "Opuntia", "Ambrosia", "Olneya", "Carnegiea", "Larrea")
inv_genus <- c("Bromus", "Schismus", "Pennisetum")

native_spe <- species %>% 
  filter(genus %in% native_genus)

inv_spe <- species %>% 
  filter(genus %in% inv_genus)

plants_native <- plants %>% 
  filter(genus %in% native_genus)

plants_invasive <- plants %>% 
  filter(genus %in% inv_genus)


```

```{r, add pre or post to data}

#native species
plants_native <- plants_native %>% 
  mutate(postingvalue = obsYear - fireYear, 
         pre_or_post = case_when(postingvalue > 0 ~ "post",
                                 postingvalue < 0 ~ "pre",
                                 postingvalue == 0 ~ "SY"),
         n_years = abs(postingvalue))

#find pre- post- for observations in the same year and replace SY in datafire with pre or post
SY <- filter(plants_native, postingvalue == 0) %>% 
  mutate(postingmonth = month - fireMonth,
    pre_or_post = case_when(postingmonth >0 ~ "post",
                            postingmonth < 0 ~ "pre",
                            postingvalue == 0 ~ "SM"))

plants_native$pre_or_post <- ifelse(plants_native$pre_or_post == "SY", SY$pre_or_post, plants_native$pre_or_post)

unique(plants_native$pre_or_post) #check if any SM (same month); would need to further categorize

plants_group_nat <-  plants_native %>% 
  group_by(fireID, pre_or_post) %>% 
  summarize(total = n())

view(plants_group_nat)

#invasive species 
plants_invasive <- plants_invasive %>% 
  mutate(postingvalue = obsYear - fireYear, 
         pre_or_post = case_when(postingvalue > 0 ~ "post",
                                 postingvalue < 0 ~ "pre",
                                 postingvalue == 0 ~ "SY"),
         n_years = abs(postingvalue))

#find pre- post- for observations in the same year and replace SY in datafire with pre or post
SY <- filter(plants_invasive, postingvalue == 0) %>% 
  mutate(postingmonth = month - fireMonth,
    pre_or_post = case_when(postingmonth >0 ~ "post",
                            postingmonth < 0 ~ "pre",
                            postingvalue == 0 ~ "SM"))

plants_invasive$pre_or_post <- ifelse(plants_invasive$pre_or_post == "SY", SY$pre_or_post, plants_invasive$pre_or_post)

unique(plants_invasive$pre_or_post) #check if any SM (same month); would need to further categorize

plants_group_inv <-  plants_invasive %>% 
  group_by(fireID, pre_or_post) %>% 
  summarize(total = n())

view(plants_group_inv)

```

```{r, make sites x species matrix for pre and post fire data}

plants <- union(plants_native, plants_invasive)

data2mat <- plants %>%
  filter(n_years > -5, n_years < 5) %>%
  select(c(fireID, genus, pre_or_post)) %>% 
  rename(sites = fireID) %>%  
  group_by(sites, genus, pre_or_post) %>% 
  summarize(abundance = n()) %>% 
  spread(genus, abundance)
  
view(data2mat)

data2mat[is.na(data2mat)] <- 0

all.pca <- rda(data2mat[,-1:-2])

cor(data2mat[,-1:-2])

summary(all.pca)

library(ggfortify)

all.pca <- prcomp(data2mat[3:8], scale = FALSE)

autoplot(all.pca, data=data2mat, colour = "pre_or_post", loadings = TRUE, 
         loadings.label = TRUE, loadings.label.size = 3,loadings.label.vjust = c(0, 1.2, 1, 1.3, 1, 0), loadings.label.hjust = c(-0.1, 0, -0.2, 0, -0.2, 0.6), legend.title = "none") + 
  geom_point(size = 3, colour = c("red3", "darkslateblue",  "red3", "darkslateblue",  "red3", "red3", "darkslateblue")) + theme_bw() + theme(legend.title = element_blank()) +
  scale_colour_manual(values = c("red3", "darkslateblue"), labels = c("post-fire", "pre-fire")) + 
  geom_hline(yintercept=0, linetype="dashed") +
  geom_vline(xintercept=0, linetype="dashed") +
  geom_text(vjust=-.5, label=(data2mat$sites)) +
  guides(color = guide_legend(override.aes = list(size = 3))) + theme(legend.text=element_text(size=12))
 


type = data2mat$pre_or_post
type

screeplot(all.pca, bstick = TRUE, type = "lines")

# data2mat_pre <- data2mat %>% 
#   filter(pre_or_post == "pre") %>% 
#   select(-c(pre_or_post)) %>% 
#   spread(genus, abundance)
# 
# data2mat_post <- data2mat %>% 
#   filter(pre_or_post == "post") %>% 
#   select(-c(pre_or_post)) %>% 
#   spread(genus, abundance)
# 
# data2mat_pre[is.na(data2mat_pre)] <- 0
# data2mat_post[is.na(data2mat_post)] <- 0
# 
# pre.pca <- rda(data2mat_pre[, -1])
# post.pca <- rda(data2mat_post[, -1])
# 
# summary(pre.pca)
# summary(post.pca)
# 
# screeplot(pre.pca, bstick = TRUE, type = "lines")
# screeplot(post.pca, bstick = TRUE, type = "lines")
# 
# plot(pre.pca)
# plot(post.pca)




```

