---
title: "Controls"
author: "Marina"
date: "11/16/2021"
output: html_document
---

```{r}
library(tidyverse)

MOJ <- read_csv("data/animals-no-burn_MOJ.csv")
SJ <- read_csv("data/animals-no-burn_SJ.csv")
SON <- read_csv("data/animals-no-burn_SON.csv")

MOJ$desert <- ifelse(is.na(MOJ$desert), "Mojave", MOJ$desert)
SJ$desert <- ifelse(is.na(SJ$desert), "San Joaquin", SJ$desert)
SON$desert <- ifelse(is.na(SON$desert), "Sonoran", SON$desert)

raw_an <- bind_rows(MOJ, SJ, SON) %>% 
  select(-FID) %>% 
  mutate(kingdom = "animalia")


MOJ_pl <- read_csv("data/plants-noburn-MOJ.csv")
SJ_pl <- read_csv("data/plants-noburn-SJ.csv")
SON_pl <- read_csv("data/plants-noburn-SON.csv")

raw_pl <- bind_rows(MOJ_pl, SJ_pl, SON_pl) %>% 
  rename(obsID = OBJECTID, dcmlLng = decimalLongitude, dcmlLtt = decimalLatitude, bssOfRc = basisOfRecord, indvdlC = individualCount, order = order_) %>% 
  select(c(obsID, species, kingdom, class, order, year, month, day, dcmlLng, dcmlLtt, indvdlC, bssOfRc, desert))

raw_pl$indvdlC <- ifelse(is.na(raw_pl$indvdlC), 0, raw_pl$indvdlC)

raw <- union(raw_an, raw_pl)

raw$desert <- as.factor(raw$desert)

unique(raw$desert)

```

Summarize how many observations in any given year for non-burned sites

```{r}
data <- raw_an %>%
  group_by(year, desert, kingdom) %>% 
  summarize(totalObs = n()) %>% 
  filter(year >1994, year <2021)

```

quick viz

```{r}
ggplot(data, aes(x = year, y = totalObs, col = desert, shape = desert)) +
  geom_point() +
  geom_smooth(method = "glm", method.args = list(family = "poisson"), aes(fill = desert)) +
  ylim(0, 1750) +
  xlim(1995, 2020) +
  ylab("Total endangered animal species \n occurrences")+
  theme_bw(base_size = 15) +
  scale_color_manual(values = c("darkgoldenrod4", "darkblue", "green4")) +
  scale_fill_manual(values = c("darkgoldenrod4", "darkblue", "green4"))

```

linear model
```{r}
ggplot(data, aes(totalObs)) +
  geom_histogram()

summary(data$totalObs)

shapiro.test(log(data$totalObs))

mean(data$totalObs)
var(data$totalObs)

library(arm)
model1 <- glm(totalObs ~ year, family = "quasipoisson", data)
model2 <- glm(totalObs ~ year, family = "poisson", data)

summary(model1)
summary(model2)

pchisq(model1$deviance, model1$df.residual, lower.tail=F)

# library(AER)
# dispersiontest(model2)
# 
# summary(model2,dispersion = 88.48696)



```


finding change over the course of the years from 1990 - 2021
```{r}
#make sure there is data for all years 1990-2021
unique(data$year)

data <- data %>% 
  filter(year >= 1990) %>% 
  group_by(desert) %>% 
  arrange(year, .by_group = TRUE) %>% 
  mutate(pct_change = ((totalObs - lag(totalObs))/lag(totalObs))*100)

#2021 was pulled earlier in the year so need to filter out
data <- data %>% 
  filter(year != 2021)

#avg change among desert
change <- data %>% 
  group_by(year) %>% 
  summarize(avg_pct_change = mean(pct_change))


```

quick viz of change for all three desert as one

```{r}
#to make bars different colors
change <- change %>% 
  mutate(pos = avg_pct_change >= 0)

sum(data$totalObs)
summary(data$totalObs)


ggplot(change, aes(year, avg_pct_change, fill = pos)) +
  geom_col()+
  theme_bw(base_size = 22) +
  theme(legend.position = "None") +
  ylab("Average \n percent change") +
  scale_fill_manual(values = c("red3", "blue4")) + ggtitle("Figure 2a")
```

quick viz for three desert individually

```{r}
#to make bars different colors

data <- data %>% 
  mutate(pos = pct_change >= 0)

ggplot(data, aes(year, pct_change, fill = pos)) +
  geom_col()+
  theme(legend.position = "None") +
  facet_grid(rows = vars(desert))
```

Compare to burned sites

```{r}
burn_data <- read_csv("data/observations.csv")
```
restructure data

```{r}
burn_data <- burn_data %>%
  group_by(obsYear) %>% 
  summarize(totalObs = n()) %>% 
  filter(obsYear >= 1990) %>% 
  filter(obsYear != 2021) %>% 
  arrange(obsYear) %>% 
  mutate(pct_change = ((totalObs - lag(totalObs))/lag(totalObs))*100) %>% 
  mutate(pos = pct_change >= 0)
  
ggplot(burn_data, aes(obsYear, pct_change, fill = pos)) +
  geom_col()+ theme_bw(base_size = 22) +
  theme(legend.position = "None") +
  ylab("Average \n percent change") +
  xlab("year") +
  scale_fill_manual(values = c("red3", "blue4")) +
  theme(legend.position = "None") + ggtitle("Figure 2b")
  
sum(burn_data$totalObs)
summary(burn_data$totalObs)

```
